name: CI

on:
  merge:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      PORT: ${{ secrets.PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Run builds
      run: npm run client:build && npm run server:build

    - name: Run tests
      run: npm test
  
  deploy:
    runs-on: ubuntu-latest
    needs: merge

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        SERVICE_ID: ${{ secrets.SERVICE_ID }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          --data '{"serviceId": "'"$SERVICE_ID"'"}' \
          https://api.render.com/v1/services/$SERVICE_ID/deploys
      